
import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Loader2, Sparkles, Brain, CheckCircle, RefreshCw, Zap } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { LandingPageTemplate, TemplateCustomization } from '@/types/template';
import { claudeAITemplateSelector } from '@/services/claudeAITemplateSelector';

interface AILandingPageGeneratorProps {
  ideaData: any;
  reports: Record<string, string>;
  onTemplateSelected: (template: LandingPageTemplate, customization: TemplateCustomization) => void;
  onManualSelection: () => void;
}

const AILandingPageGenerator = ({ 
  ideaData, 
  reports, 
  onTemplateSelected, 
  onManualSelection 
}: AILandingPageGeneratorProps) => {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState<LandingPageTemplate | null>(null);
  const [customization, setCustomization] = useState<TemplateCustomization | null>(null);
  const [reasoning, setReasoning] = useState<string>('');
  const [confidence, setConfidence] = useState<number>(0);
  const [isRegenerating, setIsRegenerating] = useState(false);
  const { toast } = useToast();

  const handleAIGenerate = async () => {
    setIsAnalyzing(true);
    try {
      console.log('Starting Claude AI analysis...');
      
      const result = await claudeAITemplateSelector.generateContentWithAI(ideaData, reports);
      
      if (result.template && result.customization) {
        setSelectedTemplate(result.template);
        setCustomization(result.customization);
        setReasoning(result.reasoning);
        setConfidence(result.confidence);
        
        toast({
          title: "Claude AI Analysis Complete!",
          description: `Selected ${result.template.name} with personalized content generated by Claude AI.`,
        });
      } else {
        toast({
          title: "AI Analysis Failed",
          description: result.reasoning || "Could not generate personalized content.",
          variant: "destructive",
        });
      }
    } catch (error: any) {
      console.error('AI generation error:', error);
      toast({
        title: "AI Generation Failed",
        description: error.message || "Could not analyze startup data with Claude AI.",
        variant: "destructive",
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleAcceptAISelection = () => {
    if (selectedTemplate && customization) {
      onTemplateSelected(selectedTemplate, customization);
    }
  };

  const handleRegenerate = async () => {
    if (!selectedTemplate) return;
    
    setIsRegenerating(true);
    try {
      const newCustomization = await claudeAITemplateSelector.regenerateContent(
        selectedTemplate.id,
        ideaData,
        reports
      );
      
      setCustomization(newCustomization);
      
      toast({
        title: "Content Regenerated!",
        description: "Claude AI has created new personalized content for your template.",
      });
    } catch (error: any) {
      toast({
        title: "Regeneration Failed",
        description: error.message || "Could not regenerate content.",
        variant: "destructive",
      });
    } finally {
      setIsRegenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* AI Generation Card */}
      <Card className="border border-gray-200 shadow-lg bg-white">
        <CardHeader className="bg-gradient-to-r from-purple-50 to-blue-50">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-purple-100 rounded-lg">
              <Brain className="h-6 w-6 text-purple-600" />
            </div>
            <div>
              <CardTitle className="flex items-center space-x-2 text-gray-900">
                <span>Claude AI-Powered Content Generation</span>
                <Badge variant="secondary" className="bg-purple-100 text-purple-800">
                  <Zap className="h-3 w-3 mr-1" />
                  Claude 3.5 Sonnet
                </Badge>
              </CardTitle>
              <CardDescription className="text-gray-600">
                Claude AI analyzes your startup data and generates highly personalized, conversion-optimized landing page content
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-6">
          <div className="space-y-4">
            {/* Analysis Preview */}
            <div className="grid md:grid-cols-3 gap-4">
              <div className="text-center p-3 bg-gray-50 rounded-lg border border-gray-200">
                <div className="text-sm text-gray-600">AI Analysis</div>
                <div className="font-semibold text-gray-900">{ideaData?.companyName ? 'Ready' : 'Preparing...'}</div>
              </div>
              <div className="text-center p-3 bg-gray-50 rounded-lg border border-gray-200">
                <div className="text-sm text-gray-600">Content Quality</div>
                <div className="font-semibold text-gray-900">Personalized</div>
              </div>
              <div className="text-center p-3 bg-gray-50 rounded-lg border border-gray-200">
                <div className="text-sm text-gray-600">Business Reports</div>
                <div className="font-semibold text-gray-900">{Object.keys(reports).length} Available</div>
              </div>
            </div>

            {/* Action Button */}
            <div className="flex items-center justify-center">
              <Button 
                onClick={handleAIGenerate} 
                disabled={isAnalyzing}
                className="bg-purple-600 hover:bg-purple-700 text-white px-8"
              >
                {isAnalyzing ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Claude AI is Analyzing...
                  </>
                ) : (
                  <>
                    <Brain className="h-4 w-4 mr-2" />
                    Generate with Claude AI
                  </>
                )}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* AI Results */}
      {selectedTemplate && customization && (
        <Card className="border-green-200 bg-green-50">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2 text-green-800">
              <CheckCircle className="h-5 w-5" />
              <span>Claude AI Recommendation Ready</span>
            </CardTitle>
            <CardDescription className="text-green-700">
              Claude AI has analyzed your startup and generated personalized, conversion-optimized content
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Template Selection Result */}
            <div className="p-4 bg-white rounded-lg border border-green-200">
              <div className="flex items-center justify-between mb-2">
                <h3 className="font-semibold text-lg text-gray-900">{selectedTemplate.name}</h3>
                <Badge variant="outline" className="bg-green-100 text-green-800 border-green-300">
                  {Math.round(confidence * 100)}% Confidence
                </Badge>
              </div>
              <p className="text-gray-600 mb-3">{selectedTemplate.description}</p>
              <div className="text-sm text-green-700 bg-green-100 p-2 rounded border border-green-200">
                <strong>Claude AI Reasoning:</strong> {reasoning}
              </div>
            </div>

            {/* Content Preview */}
            <div className="p-4 bg-white rounded-lg border border-green-200">
              <h4 className="font-semibold mb-3 text-gray-900">AI-Generated Content Preview</h4>
              <div className="space-y-2 text-sm">
                <div className="text-gray-700"><strong>Hero Title:</strong> {customization.fields.heroTitle}</div>
                <div className="text-gray-700"><strong>Hero Subtitle:</strong> {customization.fields.heroSubtitle}</div>
                <div className="text-gray-700"><strong>CTA Text:</strong> {customization.fields.ctaText}</div>
                <div className="text-gray-700"><strong>Company:</strong> {customization.companyData.name}</div>
                <div className="text-gray-700"><strong>Features:</strong> {customization.fields.feature1Title}, {customization.fields.feature2Title}, {customization.fields.feature3Title}</div>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center space-x-4">
              <Button onClick={handleAcceptAISelection} className="bg-green-600 hover:bg-green-700 text-white">
                <CheckCircle className="h-4 w-4 mr-2" />
                Use AI Recommendation
              </Button>
              <Button 
                variant="outline" 
                onClick={handleRegenerate} 
                disabled={isRegenerating}
                className="text-gray-700 border-gray-300"
              >
                {isRegenerating ? (
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                ) : (
                  <RefreshCw className="h-4 w-4 mr-2" />
                )}
                Regenerate Content
              </Button>
              <Button variant="ghost" onClick={onManualSelection} className="text-gray-600">
                Choose Manually Instead
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* How Claude AI Works */}
      <Card className="bg-white border border-gray-200">
        <CardHeader>
          <CardTitle className="text-lg text-gray-900 flex items-center space-x-2">
            <Brain className="h-5 w-5 text-purple-600" />
            <span>How Claude AI Generation Works</span>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-4 gap-4">
            <div className="text-center">
              <div className="w-8 h-8 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-2 text-sm font-semibold">1</div>
              <div className="text-sm font-medium text-gray-900">Deep Analysis</div>
              <div className="text-xs text-gray-600">Claude AI analyzes your business reports and competitive landscape</div>
            </div>
            <div className="text-center">
              <div className="w-8 h-8 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-2 text-sm font-semibold">2</div>
              <div className="text-sm font-medium text-gray-900">Smart Matching</div>
              <div className="text-xs text-gray-600">AI selects the optimal template based on your business model</div>
            </div>
            <div className="text-center">
              <div className="w-8 h-8 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-2 text-sm font-semibold">3</div>
              <div className="text-sm font-medium text-gray-900">Content Creation</div>
              <div className="text-xs text-gray-600">Generates personalized copy that speaks to your target audience</div>
            </div>
            <div className="text-center">
              <div className="w-8 h-8 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-2 text-sm font-semibold">4</div>
              <div className="text-sm font-medium text-gray-900">Optimization</div>
              <div className="text-xs text-gray-600">Optimizes messaging for conversion and brand consistency</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default AILandingPageGenerator;
