// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msrkmdkdvtkasrjyubka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcmttZGtkdnRrYXNyanl1YmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTgwMjYsImV4cCI6MjA2NTQ3NDAyNn0.gyrr4ao2v4rFHRyYIBiCZxpxv2wumDjBx9lhZHb_5Hg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);